//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musica.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaActuacion
    {
        public int IdLista { get; set; }
        public int IdActuacion { get; set; }
        public int IdMusico { get; set; }
    
        public virtual Actuacion Actuacion { get; set; }
        public virtual Musico Musico { get; set; }
    }
}
